
#All configuration items related to the core gameplay
[gameplay]
	#By default, when placing a schematic near other buildings, the already-placed buildings will show as if they were at level 5 and have a blue outline around them. You can disable that by setting this to false. [Default: true]
	neighborbuildingrendering = true
	#minecolonies.config.enablecitizenvoices.comment [Default: true]
	enablecitizenvoices = true

#All configuration related to mod compatibility
[compatibility]
	#Whether to display colony boundaries in JourneyMap [Default: true]
	mapcolonyborders = true
	#Whether to display citizen deathpoints in JourneyMap [Default: true]
	mapdeathpoints = true

