
#Everything to do with gameplay
[gameplay]
	#Set this to false to disable new players spawning with the Tinkers' Book.
	shouldSpawnWithTinkersBook = true
	#If non-empty, only this material will be shown on tools in creative and JEI (or the first valid material if this is invalid for the tool).
	#If empty, all materials will show
	showOnlyToolMaterial = ""
	#If non-empty, only material will be shown on parts in creative and JEI (or the first valid material if this is invalid for the part).
	#If empty, all materials will show
	showOnlyPartMaterial = ""

#Options related to recipes, limited options as a datapack allows most recipes to be modified
[recipes]
	#Makes wither skeletons drop necrotic bones
	witherBoneDrop = true
	#Number of nuggets produced when an ore block is melted in the smeltery. 9 nuggets would give 1 ingot
	#Range: 1 ~ 45
	smelteryNuggetsPerOre = 18
	#Makes the recipe to alloy netherite in the smeltery only cost 2 gold per netherite ingot. If false uses the vanilla rate of 4 gold per ingot. Disable if there are crafting duplications.
	cheaperNetheriteAlloy = true
	#Add a recipe that allows you to craft a piece of flint using 3 gravel
	addGravelToFlintRecipe = true
	#Allows converting wither bones to regular bones
	witherBoneConversion = true
	#Number of nuggets produced when an ore block is melted in the melter. 9 would give 1 ingot
	#Range: 1 ~ 45
	melterNuggetsPerOre = 12

#Everything to do with world generation
[worldgen]
	#Generate Cobalt
	generateCobalt = true
	#Set this to false to disable slime islands spawning in the world
	generateSlimeIslands = true
	#Generate Copper
	generateCopper = true
	#Approx Ores per Chunk
	veinCountCobalt = 8
	#Approx Ores per Chunk
	veinCountCopper = 20

