#Microphone activation type
#Allowed Values: PTT, VOICE
microphone_activation_type = "PTT"
#The threshold for voice activation in dB
#Range: -127.0 ~ 0.0
voice_activation_threshold = -50.0
#The voice chat volume
#Range: 0.0 ~ 2.0
voice_chat_volume = 1.0
#The voice chat microphone amplification
#Range: 0.0 ~ 4.0
microphone_amplification = 1.0
#The size of the audio output buffer in packets
#Higher values mean a higher latency, but less crackles
#Increase this value if you have an unstable internet connection
#Range: 1 ~ 16
output_buffer_size = 5
#The maximum amount of audio packets that are held back, if a packet arrives out of order or gets dropped
#This prevents discarding audio packets that are slightly out of order
#Set this to 0 to disable
#Range: 0 ~ 16
audio_packet_threshold = 3
#If full audio buffers should get cleared
#This potentially reduces audio latency on laggy servers
#This does currently not work on Linux
clear_full_audio_buffer = false
#The time it takes for the microphone to deactivate when using voice activation
#A value of 1 means 20 milliseconds, 2=40 ms, 3=60 ms, ...
#Range: 0 ~ 100
voice_deactivation_delay = 25
#The microphone used by the voice chat
#Empty for default device
microphone = ""
#The speaker used by the voice chat
#Empty for default device
speaker = ""
#If the microphone is muted (only when using voice activation)
muted = false
#If the voice chat is disabled (sound and microphone off)
disabled = false
#If the voice chat should use semi 3D stereo sound
stereo = true
#If the voice chat icons should be hidden
hide_icons = false
#If the group HUD should be visible
show_group_hud = true
#If the own icon should be shown when in a group
show_own_group_icon = true
#The scale of the group HUD
#Range: 0.01 ~ 10.0
group_hud_icon_scale = 2.0
#The location of the HUD icons
#Allowed Values: LEFT, RIGHT, CENTER
hud_icon_location = "LEFT"
#The orientation of the player icons in the group HUD
#Allowed Values: VERTICAL, HORIZONTAL
group_player_icon_orientation = "VERTICAL"
#The location where recordings should be saved
#Leave empty for default location
recording_destination = ""
#If noise cancellation should be enabled
denoiser = false

